version: '3.9'

services:
  node1:
    image: cluster:latest
    environment:
      - NODE=localhost
    ports:
      - 3031:3333

  node2:
    image: cluster:latest
    environment:
      - NODE=node1
    ports:
      - 3032:3333

  node3:
    image: cluster:latest
    environment:
      - NODE=node1
    ports:
      - 3033:3333

